# Mark Shust's Docker Configuration for Magento
# (https://github.com/markshust/docker-magento)
#
# Version 32.0.1

version: "3"

services:
  app:
    volumes: &appvolumes
      # Host mounts with performance penalty, only put what is necessary here
      - ./src/app/code:/var/www/html/app/code:delegated
      - ./src/app/design:/var/www/html/app/design:delegated
      - ./src/app/etc:/var/www/html/app/etc:delegated
      - ./src/composer.json:/var/www/html/composer.json:delegated
      - ./src/composer.lock:/var/www/html/composer.lock:delegated
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:delegated
      #- ./src/auth.json:/var/www/html/auth.json:delegated
      #- ./src/m2-hotfixes:/var/www/html/m2-hotfixes:delegated
      #- ./src/patches:/var/www/html/patches:delegated
      #- ./src/var/log:/var/www/html/var/log:delegated
      #- ./src/var/report:/var/www/html/var/report:delegated
      # Linux only: remove the above lines and mount the entire src directory with:
      #- ./src:/var/www/html:delegated

  phpfpm:
    volumes: *appvolumes
    # Linux only: host.docker.internal doesn't exist https://github.com/docker/for-linux/issues/264
    # Uncomment two lines below & replace IP with result of: docker run --rm alpine ip route | awk 'NR==1 {print $3}'
    #extra_hosts:
    #  - "host.docker.internal:IP"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.6.2
    ports:
      - 5601:5601

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  volumes: *appvolumes

  vue-storefront:
    image: docker.pkg.github.com/skinups/vue-storefront/vue-server:latest
    environment:
      - API_URL=http://bergamot:8080
      - IMAGES_BASE_URL=http://bergamot:8080/img/
      - ELASTICSEARCH_HOST=/api/catalog
      - CART_ENDPOINT=/api/cart/create?token={{token}}
      - CART_UPDATEITEM_ENDPOINT=/api/cart/update?token={{token}}&cartId={{cartId}}
      - CART_DELETEITEM_ENDPOINT=/api/cart/delete?token={{token}}&cartId={{cartId}}
      - CART_PULL_ENDPOINT=/api/cart/pull?token={{token}}&cartId={{cartId}}
      - CART_TOTALS_ENDPOINT=/api/cart/totals?token={{token}}&cartId={{cartId}}
      - CART_PAYMENTMETHODS_ENDPOINT=/api/cart/payment-methods?token={{token}}&cartId={{cartId}}
      - CART_SHIPPINGMETHODS_ENDPOINT=/api/cart/shipping-methods?token={{token}}&cartId={{cartId}}
      - CART_SHIPPINGINFO_ENDPOINT=/api/cart/shipping-information?token={{token}}&cartId={{cartId}}
      - CART_COLLECTTOTALS_ENDPOINT=/api/cart/collect-totals?token={{token}}&cartId={{cartId}}
      - CART_DELETECOUPON_ENDPOINT=/api/cart/delete-coupon?token={{token}}&cartId={{cartId}}
      - CART_APPLYCOUPON_ENDPOINT=/api/cart/apply-coupon?token={{token}}&cartId={{cartId}}&coupon={{coupon}}
      - PRODUCTS_ENDPOINT=/api/product
      - ORDERS_ENDPOINT=/api/order
      - REVIEWS_CREATE_ENDPOINT=/api/review/create?token={{token}}
      - USERS_ENDPOINT=/api/user
      - USERS_HISTORY_ENDPOINT=/api/user/order-history?token={{token}}&pageSize={{pageSize}}&currentPage={{currentPage}}
      - USERS_RESETPASSWORD_ENDPOINT=/api/user/reset-password
      - USERS_CREATEPASSWORD_ENDPOINT=/api/user/create-password
      - USERS_CHANGEPASSWORD_ENDPOINT=/api/user/change-password?token={{token}}
      - USERS_LOGIN_ENDPOINT=/api/user/login
      - USERS_CREATE_ENDPOINT=/api/user/create
      - USERS_ME_ENDPOINT=/api/user/me?token={{token}}
      - USERS_REFRESH_ENDPOINT=/api/user/refresh
      - STOCK_ENDPOINT=/api/stock
      - NEWSLETTER_ENDPOINT=/api/ext/mailchimp-subscribe/subscribe
      - MAILER_SEND=/api/ext/mail-service/send-email
      - MAILER_TOKEN=/api/ext/mail-service/get-token
    ports:
      - "3000:3000"

  vue-storefront-api:
    image: docker.pkg.github.com/skinups/vue-storefront-api/vue-server-api:latest
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - DRM_URL=http://192.168.1.65:3100/v1/api/assets
      - REDIS_HOST=redis
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_SECURE=
      - MAIL_USER=test
      - MAIL_PASSWORD=test
      - MAGENTO2_IMG_URL=http://app/pub/media/catalog/product
      - MAGENTO2_ASSET_PATH=html/pub/media
      - MAGENTO2_URL=http://app
      - MAGENTO2_API_URL=http://bergamot/rest
      - MAGENTO2_ASSET_PATH=var/pub/media
      - MAGENTO2_CONSUMER_KEY=zxso0bss73wze2orc5pynoansscir96c
      - MAGENTO2_CONSUMER_SECRET=8t4yota61tspirlw8mkzba4j85l4nqd1
      - MAGENTO2_ACCESS_TOKEN=gn23nok10wgsm63avjzd6do4t0qgyxz0
      - MAGENTO2_ACCESS_TOKEN_SECRET=vw3d79cvk0k7zb0brrg84amdkm88z9r1
    ports:
      - "8080:8080"
    volumes:
      - appdata:/home/node/vue-storefront-api/html
